# Generated by Django 3.2 on 2024-07-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=255)),
                ('response_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link')], max_length=1000)),
                ('content', models.TextField()),
                ('ai_answer', models.BooleanField(default=False)),
            ],
        ),
    ]
